//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип оплаты.
    /// </summary>
    // *** Start programmer edit section *** (tТипОплаты CustomAttributes)

    // *** End programmer edit section *** (tТипОплаты CustomAttributes)
    public enum tТипОплаты
    {
        
        // *** Start programmer edit section *** (tТипОплаты.Картой CustomAttributes)

        // *** End programmer edit section *** (tТипОплаты.Картой CustomAttributes)
        Картой,
        
        // *** Start programmer edit section *** (tТипОплаты.Наличные CustomAttributes)

        // *** End programmer edit section *** (tТипОплаты.Наличные CustomAttributes)
        Наличные,
    }
}
