//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуга.
    /// </summary>
    // *** Start programmer edit section *** (Услуга CustomAttributes)

    // *** End programmer edit section *** (Услуга CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Услуга : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодУслуги;
        
        private string fНаименование;
        
        private IIS.Test.Запись fЗапись;
        
        // *** Start programmer edit section *** (Услуга CustomMembers)

        // *** End programmer edit section *** (Услуга CustomMembers)

        
        /// <summary>
        /// КодУслуги.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.КодУслуги CustomAttributes)

        // *** End programmer edit section *** (Услуга.КодУслуги CustomAttributes)
        public virtual int КодУслуги
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.КодУслуги Get start)

                // *** End programmer edit section *** (Услуга.КодУслуги Get start)
                int result = this.fКодУслуги;
                // *** Start programmer edit section *** (Услуга.КодУслуги Get end)

                // *** End programmer edit section *** (Услуга.КодУслуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.КодУслуги Set start)

                // *** End programmer edit section *** (Услуга.КодУслуги Set start)
                this.fКодУслуги = value;
                // *** Start programmer edit section *** (Услуга.КодУслуги Set end)

                // *** End programmer edit section *** (Услуга.КодУслуги Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.Наименование CustomAttributes)

        // *** End programmer edit section *** (Услуга.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.Наименование Get start)

                // *** End programmer edit section *** (Услуга.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Услуга.Наименование Get end)

                // *** End programmer edit section *** (Услуга.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.Наименование Set start)

                // *** End programmer edit section *** (Услуга.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Услуга.Наименование Set end)

                // *** End programmer edit section *** (Услуга.Наименование Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Test.Запись.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.Запись CustomAttributes)

        // *** End programmer edit section *** (Услуга.Запись CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Запись"})]
        public virtual IIS.Test.Запись Запись
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.Запись Get start)

                // *** End programmer edit section *** (Услуга.Запись Get start)
                IIS.Test.Запись result = this.fЗапись;
                // *** Start programmer edit section *** (Услуга.Запись Get end)

                // *** End programmer edit section *** (Услуга.Запись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.Запись Set start)

                // *** End programmer edit section *** (Услуга.Запись Set start)
                this.fЗапись = value;
                // *** Start programmer edit section *** (Услуга.Запись Set end)

                // *** End programmer edit section *** (Услуга.Запись Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of Услуга.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУслуга CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУслуга CustomAttributes)
    public class DetailArrayOfУслуга : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Test.DetailArrayOfУслуга members)

        // *** End programmer edit section *** (IIS.Test.DetailArrayOfУслуга members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Услуга by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Услуга.
        /// </summary>
        public DetailArrayOfУслуга(IIS.Test.Запись fЗапись) : 
                base(typeof(Услуга), ((ICSSoft.STORMNET.DataObject)(fЗапись)))
        {
        }
        
        public IIS.Test.Услуга this[int index]
        {
            get
            {
                return ((IIS.Test.Услуга)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Test.Услуга dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
